// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD5T8ck7oa0cxT9vghvp05qA_dmVvYcLU',
    appId: '1:238173822948:web:7dbbb4fdedc872799071f1',
    messagingSenderId: '238173822948',
    projectId: 'procodder-db7f8',
    authDomain: 'procodder-db7f8.firebaseapp.com',
    storageBucket: 'procodder-db7f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgn-jgG1gzY37_7VpupJZl3T05qW8cn0U',
    appId: '1:238173822948:android:57f8b0fc0cb8ff2c9071f1',
    messagingSenderId: '238173822948',
    projectId: 'procodder-db7f8',
    storageBucket: 'procodder-db7f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSZ6E_JBBIYyir-aYDd-mZ1YXhT0-BCO4',
    appId: '1:238173822948:ios:e38aa0e3f229b8f09071f1',
    messagingSenderId: '238173822948',
    projectId: 'procodder-db7f8',
    storageBucket: 'procodder-db7f8.appspot.com',
    iosBundleId: 'com.example.procodder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSZ6E_JBBIYyir-aYDd-mZ1YXhT0-BCO4',
    appId: '1:238173822948:ios:3883722a324735499071f1',
    messagingSenderId: '238173822948',
    projectId: 'procodder-db7f8',
    storageBucket: 'procodder-db7f8.appspot.com',
    iosBundleId: 'com.example.procodder.RunnerTests',
  );
}
